name: f
description: A simple shortcut, command line interface (CLI) for Flutter to increase productivity and happiness.
version: 0.1.2
homepage: https://github.com/salkuadrat/f
repository: https://github.com/salkuadrat/f

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  f:
