name: f
description: A simple shortcut, command line interface (CLI) for a lazy (a.k.a effective) Flutter developer in order to increase productivity and happiness.
version: 0.0.5
homepage: https://github.com/salkuadrat/f
repository: https://github.com/salkuadrat/f

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  process_run: ^0.12.2+2
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  f:
